#!/bin/bash

# This script builds the Flutter iOS app with environment variables to remove the -G flag
# It uses a simpler approach without requiring the xcodeproj gem

set -e  # Exit on error

# Get the absolute path to the project root directory
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "Project root: $PROJECT_ROOT"

# Make sure compiler wrappers are executable
chmod +x "$PROJECT_ROOT/compiler_wrappers/clang" "$PROJECT_ROOT/compiler_wrappers/clang++"

# Add compiler wrappers to the beginning of PATH
export PATH="$PROJECT_ROOT/compiler_wrappers:$PATH"
echo "Modified PATH to use compiler wrappers:"
echo "PATH=$PATH"

# Set environment variables to force Xcode to use our compiler wrappers
export CC="$PROJECT_ROOT/compiler_wrappers/clang"
export CXX="$PROJECT_ROOT/compiler_wrappers/clang++"
export LDPLUSPLUS="$PROJECT_ROOT/compiler_wrappers/clang++"
export LDFLAGS="-Wl,-no_compact_unwind"

echo "Compiler environment variables set to use wrappers:"
echo "CC=$CC"
echo "CXX=$CXX"
echo "LDPLUSPLUS=$LDPLUSPLUS"

# Run flutter pub get to ensure Flutter configuration files exist
echo "Running flutter pub get..."
flutter pub get

# Remove -G flag from xcconfig files
echo "Removing -G flag from xcconfig files..."
find "$PROJECT_ROOT/ios" -name "*.xcconfig" -exec sed -i '' 's/-G//g' {} \;

# Remove -G flag from project files
echo "Removing -G flag from project files..."
find "$PROJECT_ROOT/ios" -name "*.pbxproj" -exec sed -i '' 's/-G//g' {} \;

# Create a custom xcconfig file to override any remaining -G flags
echo "Creating custom xcconfig file..."
cat > "$PROJECT_ROOT/ios/Flutter/NoGFlag.xcconfig" << EOF
// This file is generated by build_ios_simple.sh
// It removes the -G flag from the build process

OTHER_CFLAGS = $(inherited)
OTHER_CXXFLAGS = $(inherited)
OTHER_SWIFT_FLAGS = $(inherited)

// Force the compiler to ignore the -G flag
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) DISABLE_G_FLAG=1
EOF

# Update Debug.xcconfig and Release.xcconfig to include our custom xcconfig
echo "Updating xcconfig files..."
for config_file in "$PROJECT_ROOT/ios/Flutter/Debug.xcconfig" "$PROJECT_ROOT/ios/Flutter/Release.xcconfig"; do
  if [ -f "$config_file" ]; then
    if ! grep -q "NoGFlag.xcconfig" "$config_file"; then
      echo '#include "NoGFlag.xcconfig"' >> "$config_file"
      echo "Updated $config_file to include NoGFlag.xcconfig"
    fi
  fi
done

# Create a script to modify the Xcode build process
echo "Creating Xcode build modifier script..."
cat > "$PROJECT_ROOT/ios/modify_xcode_build.sh" << 'EOF'
#!/bin/bash

# This script modifies the Xcode build process to remove the -G flag
# It is executed before building the app

# Get the path to the compiler wrappers
WRAPPER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../compiler_wrappers" && pwd)"

# Add compiler wrappers to the beginning of PATH
export PATH="$WRAPPER_DIR:$PATH"
echo "Modified PATH to use compiler wrappers: $PATH"

# Set environment variables to force Xcode to use our compiler wrappers
export CC="$WRAPPER_DIR/clang"
export CXX="$WRAPPER_DIR/clang++"
export LDPLUSPLUS="$WRAPPER_DIR/clang++"
export LDFLAGS="-Wl,-no_compact_unwind"

echo "Compiler environment variables set to use wrappers"
echo "CC=$CC"
echo "CXX=$CXX"
echo "LDPLUSPLUS=$LDPLUSPLUS"

# Remove -G flag from any newly generated xcconfig files
find "${SRCROOT}" -name "*.xcconfig" -exec sed -i '' 's/-G//g' {} \;
echo "Removed -G flag from xcconfig files"
EOF

chmod +x "$PROJECT_ROOT/ios/modify_xcode_build.sh"

# Run pod install with our compiler wrappers
echo "Running pod install with compiler wrappers..."
cd "$PROJECT_ROOT/ios"
pod install

# Set FLUTTER_XCODE_ONLY_ACTIVE_ARCH=YES to build only for the active architecture
export FLUTTER_XCODE_ONLY_ACTIVE_ARCH=YES

# Set OTHER_CFLAGS and OTHER_CXXFLAGS to override any -G flags
export OTHER_CFLAGS=""
export OTHER_CXXFLAGS=""

# Build the Flutter app for iOS simulator
echo "Building Flutter app with modified compiler settings..."
cd "$PROJECT_ROOT"

# Source the Xcode build modifier script to set up the environment
source "$PROJECT_ROOT/ios/modify_xcode_build.sh"

# Run the Flutter build with the --no-codesign flag to skip code signing
flutter build ios --simulator --no-codesign

echo "Build completed!"
