#!/bin/bash

# This script directly builds the Flutter app using compiler wrappers to remove the -G flag
# It sets up the environment to use our compiler wrappers and runs the Flutter build

set -e  # Exit on error

# Get the absolute path to the project root directory
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "Project root: $PROJECT_ROOT"

# Make sure compiler wrappers are executable
chmod +x "$PROJECT_ROOT/compiler_wrappers/clang" "$PROJECT_ROOT/compiler_wrappers/clang++"

# Add compiler wrappers to the beginning of PATH
export PATH="$PROJECT_ROOT/compiler_wrappers:$PATH"
echo "Modified PATH to use compiler wrappers:"
echo "PATH=$PATH"

# Clean the Flutter project
echo "Cleaning Flutter project..."
flutter clean

# Clean CocoaPods
echo "Cleaning CocoaPods..."
cd "$PROJECT_ROOT/ios"
rm -rf Pods
rm -f Podfile.lock

# Install CocoaPods
echo "Installing CocoaPods..."
pod install

# Remove -G flag from xcconfig files
echo "Removing -G flag from xcconfig files..."
find "$PROJECT_ROOT/ios" -name "*.xcconfig" -exec sed -i '' 's/-G//g' {} \;

# Remove -G flag from project files
echo "Removing -G flag from project files..."
find "$PROJECT_ROOT/ios" -name "*.pbxproj" -exec sed -i '' 's/-G//g' {} \;

# Create a custom xcconfig file to override any remaining -G flags
echo "Creating custom xcconfig file..."
cat > "$PROJECT_ROOT/ios/Flutter/NoGFlag.xcconfig" << EOF
// This file is generated by direct_build.sh
// It removes the -G flag from the build process

OTHER_CFLAGS = $(inherited)
OTHER_CXXFLAGS = $(inherited)
OTHER_SWIFT_FLAGS = $(inherited)

// Force the compiler to ignore the -G flag
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) DISABLE_G_FLAG=1
EOF

# Update Debug.xcconfig and Release.xcconfig to include our custom xcconfig
echo "Updating xcconfig files..."
for config_file in "$PROJECT_ROOT/ios/Flutter/Debug.xcconfig" "$PROJECT_ROOT/ios/Flutter/Release.xcconfig"; do
  if [ -f "$config_file" ]; then
    if ! grep -q "NoGFlag.xcconfig" "$config_file"; then
      echo '#include "NoGFlag.xcconfig"' >> "$config_file"
      echo "Updated $config_file to include NoGFlag.xcconfig"
    fi
  fi
done

# Set environment variables to force Xcode to use our compiler wrappers
export CC="$PROJECT_ROOT/compiler_wrappers/clang"
export CXX="$PROJECT_ROOT/compiler_wrappers/clang++"
export LDPLUSPLUS="$PROJECT_ROOT/compiler_wrappers/clang++"

# Create a temporary script to modify the Xcode build process
TEMP_SCRIPT="$PROJECT_ROOT/ios/modify_xcode_build.rb"
cat > "$TEMP_SCRIPT" << 'EOF'
#!/usr/bin/env ruby

require 'xcodeproj'

# Path to the Xcode project
project_path = File.join(Dir.pwd, 'Runner.xcodeproj')
project = Xcodeproj::Project.open(project_path)

# Find the Runner target
target = project.targets.find { |t| t.name == 'Runner' }
if target.nil?
  puts "Error: Could not find Runner target"
  exit 1
end

# Add a Run Script Phase to remove the -G flag
phase_name = "Remove -G Flag"
existing_phase = target.build_phases.find { |p| p.is_a?(Xcodeproj::Project::Object::PBXShellScriptBuildPhase) && p.name == phase_name }

if existing_phase.nil?
  puts "Adding Run Script Phase to remove -G flag"
  phase = target.new_shell_script_build_phase(phase_name)
  phase.shell_script = <<-SCRIPT
# Remove -G flag from compiler arguments
export PATH="${SRCROOT}/../compiler_wrappers:$PATH"
echo "Modified PATH to use compiler wrappers: $PATH"
  SCRIPT
  
  # Move the phase to be before the Compile Sources phase
  compile_phase_index = target.build_phases.find_index { |p| p.is_a?(Xcodeproj::Project::Object::PBXSourcesBuildPhase) }
  if compile_phase_index
    target.build_phases.move_from(target.build_phases.count - 1, compile_phase_index)
  end
else
  puts "Run Script Phase to remove -G flag already exists"
end

# Save the project
project.save
puts "Xcode project updated successfully"
EOF

chmod +x "$TEMP_SCRIPT"

# Run the script to modify the Xcode project
echo "Modifying Xcode project..."
cd "$PROJECT_ROOT/ios"
ruby "$TEMP_SCRIPT"

# Remove the temporary script
rm "$TEMP_SCRIPT"

# Build the Flutter app for iOS simulator
echo "Building Flutter app with modified compiler settings..."
cd "$PROJECT_ROOT"
flutter build ios --simulator --no-codesign

echo "Build completed!"
