#!/bin/bash

# This script fixes the -G flag issue in iOS build without cleaning Flutter
# It sets up compiler wrappers and modifies build settings

set -e  # Exit on error

# Get the absolute path to the project root directory
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "Project root: $PROJECT_ROOT"

# Make sure compiler wrappers are executable
chmod +x "$PROJECT_ROOT/compiler_wrappers/clang" "$PROJECT_ROOT/compiler_wrappers/clang++"

# Add compiler wrappers to the beginning of PATH
export PATH="$PROJECT_ROOT/compiler_wrappers:$PATH"
echo "Modified PATH to use compiler wrappers:"
echo "PATH=$PATH"

# Run flutter pub get to ensure Flutter configuration files exist
echo "Running flutter pub get..."
flutter pub get

# Remove -G flag from xcconfig files
echo "Removing -G flag from xcconfig files..."
find "$PROJECT_ROOT/ios" -name "*.xcconfig" -exec sed -i '' 's/-G//g' {} \;

# Remove -G flag from project files
echo "Removing -G flag from project files..."
find "$PROJECT_ROOT/ios" -name "*.pbxproj" -exec sed -i '' 's/-G//g' {} \;

# Create a custom xcconfig file to override any remaining -G flags
echo "Creating custom xcconfig file..."
cat > "$PROJECT_ROOT/ios/Flutter/NoGFlag.xcconfig" << EOF
// This file is generated by fix_g_flag.sh
// It removes the -G flag from the build process

OTHER_CFLAGS = $(inherited)
OTHER_CXXFLAGS = $(inherited)
OTHER_SWIFT_FLAGS = $(inherited)

// Force the compiler to ignore the -G flag
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) DISABLE_G_FLAG=1
EOF

# Update Debug.xcconfig and Release.xcconfig to include our custom xcconfig
echo "Updating xcconfig files..."
for config_file in "$PROJECT_ROOT/ios/Flutter/Debug.xcconfig" "$PROJECT_ROOT/ios/Flutter/Release.xcconfig"; do
  if [ -f "$config_file" ]; then
    if ! grep -q "NoGFlag.xcconfig" "$config_file"; then
      echo '#include "NoGFlag.xcconfig"' >> "$config_file"
      echo "Updated $config_file to include NoGFlag.xcconfig"
    fi
  fi
done

# Set environment variables to force Xcode to use our compiler wrappers
export CC="$PROJECT_ROOT/compiler_wrappers/clang"
export CXX="$PROJECT_ROOT/compiler_wrappers/clang++"
export LDPLUSPLUS="$PROJECT_ROOT/compiler_wrappers/clang++"

# Run pod install with our compiler wrappers
echo "Running pod install with compiler wrappers..."
cd "$PROJECT_ROOT/ios"
pod install

# Create a script to be used during the build process
echo "Creating build helper script..."
cat > "$PROJECT_ROOT/ios/remove_g_flag_during_build.sh" << 'EOF'
#!/bin/bash

# This script is executed during the Xcode build process
# It ensures the -G flag is removed from all compiler invocations

# Get the path to the compiler wrappers
WRAPPER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../compiler_wrappers" && pwd)"

# Add compiler wrappers to the beginning of PATH
export PATH="$WRAPPER_DIR:$PATH"
echo "Modified PATH to use compiler wrappers: $PATH"

# Set environment variables to force Xcode to use our compiler wrappers
export CC="$WRAPPER_DIR/clang"
export CXX="$WRAPPER_DIR/clang++"
export LDPLUSPLUS="$WRAPPER_DIR/clang++"

echo "Compiler environment variables set to use wrappers"
echo "CC=$CC"
echo "CXX=$CXX"
echo "LDPLUSPLUS=$LDPLUSPLUS"

# Remove -G flag from any newly generated xcconfig files
find "${SRCROOT}" -name "*.xcconfig" -exec sed -i '' 's/-G//g' {} \;
echo "Removed -G flag from xcconfig files"
EOF

chmod +x "$PROJECT_ROOT/ios/remove_g_flag_during_build.sh"

# Build the Flutter app for iOS simulator
echo "Building Flutter app with modified compiler settings..."
cd "$PROJECT_ROOT"

# Set environment variables for the build
export CC="$PROJECT_ROOT/compiler_wrappers/clang"
export CXX="$PROJECT_ROOT/compiler_wrappers/clang++"
export LDPLUSPLUS="$PROJECT_ROOT/compiler_wrappers/clang++"

# Run the Flutter build
flutter build ios --simulator --no-codesign

echo "Build completed!"
