#!/bin/bash

# This script specifically targets simulator architecture flags to fix the -G flag issue
# It focuses on modifying the build settings for the simulator architecture

set -e  # Exit on error

# Get the absolute path to the project root directory
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "Project root: $PROJECT_ROOT"

# Make sure compiler wrappers are executable
chmod +x "$PROJECT_ROOT/compiler_wrappers/clang" "$PROJECT_ROOT/compiler_wrappers/clang++"

# Add compiler wrappers to the beginning of PATH
export PATH="$PROJECT_ROOT/compiler_wrappers:$PATH"
echo "Modified PATH to use compiler wrappers:"
echo "PATH=$PATH"

# Set environment variables to force Xcode to use our compiler wrappers
export CC="$PROJECT_ROOT/compiler_wrappers/clang"
export CXX="$PROJECT_ROOT/compiler_wrappers/clang++"
export LDPLUSPLUS="$PROJECT_ROOT/compiler_wrappers/clang++"

# Set Flutter environment variables to modify the build process
export FLUTTER_XCODE_ONLY_ACTIVE_ARCH=YES
export FLUTTER_BUILD_MODE=debug

echo "Compiler environment variables set:"
echo "CC=$CC"
echo "CXX=$CXX"
echo "LDPLUSPLUS=$LDPLUSPLUS"
echo "FLUTTER_XCODE_ONLY_ACTIVE_ARCH=$FLUTTER_XCODE_ONLY_ACTIVE_ARCH"

# Create a custom xcconfig file specifically for simulator architecture
echo "Creating custom xcconfig file for simulator architecture..."
cat > "$PROJECT_ROOT/ios/Flutter/SimulatorArch.xcconfig" << EOF
// This file is generated by fix_simulator_arch.sh
// It specifically targets simulator architecture flags

// Explicitly set simulator architectures without -G flag
ARCHS_STANDARD = arm64 x86_64
EXCLUDED_ARCHS[sdk=iphonesimulator*] = 
VALID_ARCHS = arm64 x86_64

// Override compiler flags for simulator
OTHER_CFLAGS[sdk=iphonesimulator*] = \$(inherited)
OTHER_CXXFLAGS[sdk=iphonesimulator*] = \$(inherited)
OTHER_LDFLAGS[sdk=iphonesimulator*] = \$(inherited)

// Disable -G flag for simulator builds
COMPILER_INDEX_STORE_ENABLE[sdk=iphonesimulator*] = NO
EOF

# Update Debug.xcconfig to include our custom simulator architecture xcconfig
echo "Updating Debug.xcconfig to include SimulatorArch.xcconfig..."
DEBUG_XCCONFIG="$PROJECT_ROOT/ios/Flutter/Debug.xcconfig"
if [ -f "$DEBUG_XCCONFIG" ]; then
  if ! grep -q "SimulatorArch.xcconfig" "$DEBUG_XCCONFIG"; then
    echo '#include "SimulatorArch.xcconfig"' >> "$DEBUG_XCCONFIG"
    echo "Updated Debug.xcconfig to include SimulatorArch.xcconfig"
  fi
fi

# Create a custom Flutter config file to override any remaining -G flags
echo "Creating custom Flutter config file..."
cat > "$PROJECT_ROOT/ios/Flutter/CustomFlutterConfig.xcconfig" << EOF
// This file is generated by fix_simulator_arch.sh
// It removes the -G flag from the Flutter build process

// Force the compiler to ignore the -G flag
GCC_PREPROCESSOR_DEFINITIONS = \$(inherited) DISABLE_G_FLAG=1

// Explicitly disable compiler index store for all builds
COMPILER_INDEX_STORE_ENABLE = NO
EOF

# Update Debug.xcconfig to include our custom Flutter config
echo "Updating Debug.xcconfig to include CustomFlutterConfig.xcconfig..."
if [ -f "$DEBUG_XCCONFIG" ]; then
  if ! grep -q "CustomFlutterConfig.xcconfig" "$DEBUG_XCCONFIG"; then
    echo '#include "CustomFlutterConfig.xcconfig"' >> "$DEBUG_XCCONFIG"
    echo "Updated Debug.xcconfig to include CustomFlutterConfig.xcconfig"
  fi
fi

# Run flutter pub get to ensure Flutter configuration files exist
echo "Running flutter pub get..."
flutter pub get

# Remove -G flag from all xcconfig files
echo "Removing -G flag from all xcconfig files..."
find "$PROJECT_ROOT/ios" -name "*.xcconfig" -exec sed -i '' 's/-G//g' {} \;

# Run pod install with our compiler wrappers
echo "Running pod install with compiler wrappers..."
cd "$PROJECT_ROOT/ios"
pod install

# Get available iOS simulators
echo "Available iOS simulators:"
xcrun simctl list devices | grep -i iphone

# Automatically select a simulator (prefer booted ones)
# Extract the device ID properly using awk
DEVICE_ID=$(xcrun simctl list devices | grep -i iphone | grep -i "booted" | awk -F'[()]' '{print $2}' | head -n 1)

if [ -z "$DEVICE_ID" ]; then
  # If no booted simulator, get the first available one
  DEVICE_ID=$(xcrun simctl list devices | grep -i iphone | awk -F'[()]' '{print $2}' | head -n 1)
fi

if [ -z "$DEVICE_ID" ]; then
  echo "Error: No iPhone simulator found"
  exit 1
fi

echo "Using simulator device ID: $DEVICE_ID"

# Run Flutter directly with the specified device
echo "Running Flutter with modified environment..."
cd "$PROJECT_ROOT"
flutter run -d "$DEVICE_ID"
