#!/bin/bash

# This script specifically targets simulator architecture flags to fix the -G flag issue
# It modifies the build process to remove the -G flag from simulator architecture flags

set -e  # Exit on error

# Get the absolute path to the project root directory
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "Project root: $PROJECT_ROOT"

# Make sure compiler wrappers are executable
chmod +x "$PROJECT_ROOT/compiler_wrappers/clang" "$PROJECT_ROOT/compiler_wrappers/clang++"

# Add compiler wrappers to the beginning of PATH
export PATH="$PROJECT_ROOT/compiler_wrappers:$PATH"
echo "Modified PATH to use compiler wrappers:"
echo "PATH=$PATH"

# Set environment variables to force Xcode to use our compiler wrappers
export CC="$PROJECT_ROOT/compiler_wrappers/clang"
export CXX="$PROJECT_ROOT/compiler_wrappers/clang++"
export LDPLUSPLUS="$PROJECT_ROOT/compiler_wrappers/clang++"

# Set Flutter environment variables to modify the build process
export FLUTTER_XCODE_ONLY_ACTIVE_ARCH=YES
export FLUTTER_BUILD_MODE=debug

echo "Compiler environment variables set:"
echo "CC=$CC"
echo "CXX=$CXX"
echo "LDPLUSPLUS=$LDPLUSPLUS"
echo "FLUTTER_XCODE_ONLY_ACTIVE_ARCH=$FLUTTER_XCODE_ONLY_ACTIVE_ARCH"

# Run flutter pub get to ensure Flutter configuration files exist
echo "Running flutter pub get..."
flutter pub get

# Remove -G flag from xcconfig files
echo "Removing -G flag from xcconfig files..."
find "$PROJECT_ROOT/ios" -name "*.xcconfig" -exec sed -i '' 's/-G//g' {} \;

# Create a custom xcconfig file to override any remaining -G flags
echo "Creating custom xcconfig file..."
cat > "$PROJECT_ROOT/ios/Flutter/CustomBuild.xcconfig" << EOF
// This file is generated by fix_simulator_flags.sh
// It removes the -G flag from the build process

OTHER_CFLAGS = \$(inherited)
OTHER_CXXFLAGS = \$(inherited)
OTHER_SWIFT_FLAGS = \$(inherited)

// Force the compiler to ignore the -G flag
GCC_PREPROCESSOR_DEFINITIONS = \$(inherited) DISABLE_G_FLAG=1

// Explicitly set simulator architectures without -G flag
ARCHS_STANDARD = arm64 x86_64
EXCLUDED_ARCHS[sdk=iphonesimulator*] = 
VALID_ARCHS = arm64 x86_64
EOF

# Update Debug.xcconfig and Release.xcconfig to include our custom xcconfig
echo "Updating xcconfig files..."
for config_file in "$PROJECT_ROOT/ios/Flutter/Debug.xcconfig" "$PROJECT_ROOT/ios/Flutter/Release.xcconfig"; do
  if [ -f "$config_file" ]; then
    if ! grep -q "CustomBuild.xcconfig" "$config_file"; then
      echo '#include "CustomBuild.xcconfig"' >> "$config_file"
      echo "Updated $config_file to include CustomBuild.xcconfig"
    fi
  fi
done

# Create a script to modify the Xcode build process
echo "Creating Xcode build modifier script..."
cat > "$PROJECT_ROOT/ios/modify_xcode_build.sh" << 'EOF'
#!/bin/bash

# This script modifies the Xcode build process to remove the -G flag
# It is executed before building the app

# Get the path to the compiler wrappers
WRAPPER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../compiler_wrappers" && pwd)"

# Add compiler wrappers to the beginning of PATH
export PATH="$WRAPPER_DIR:$PATH"
echo "Modified PATH to use compiler wrappers: $PATH"

# Set environment variables to force Xcode to use our compiler wrappers
export CC="$WRAPPER_DIR/clang"
export CXX="$WRAPPER_DIR/clang++"
export LDPLUSPLUS="$WRAPPER_DIR/clang++"

# Remove -G flag from any newly generated xcconfig files
find "${SRCROOT}" -name "*.xcconfig" -exec sed -i '' 's/-G//g' {} \;
echo "Removed -G flag from xcconfig files"

# Modify the build settings to remove -G flag
export OTHER_CFLAGS="${OTHER_CFLAGS//-G/}"
export OTHER_CXXFLAGS="${OTHER_CXXFLAGS//-G/}"
export OTHER_LDFLAGS="${OTHER_LDFLAGS//-G/}"

echo "Modified build settings to remove -G flag"
EOF

chmod +x "$PROJECT_ROOT/ios/modify_xcode_build.sh"

# Modify the Podfile to add a post_install hook to remove the -G flag
echo "Modifying Podfile to add post_install hook..."
PODFILE="$PROJECT_ROOT/ios/Podfile"
if [ -f "$PODFILE" ]; then
  # Check if the post_install hook already exists
  if grep -q "post_install do |installer|" "$PODFILE"; then
    # Modify the existing post_install hook
    sed -i '' '/post_install do |installer|/,/end/ s/end/  # Remove -G flag from all build configurations\n  installer.pods_project.targets.each do |target|\n    target.build_configurations.each do |config|\n      config.build_settings["OTHER_CFLAGS"] = config.build_settings["OTHER_CFLAGS"].to_s.gsub(/-G/, "")\n      config.build_settings["OTHER_CXXFLAGS"] = config.build_settings["OTHER_CXXFLAGS"].to_s.gsub(/-G/, "")\n      config.build_settings["OTHER_LDFLAGS"] = config.build_settings["OTHER_LDFLAGS"].to_s.gsub(/-G/, "")\n    end\n  end\nend/' "$PODFILE"
  else
    # Add a new post_install hook
    cat >> "$PODFILE" << 'EOF'

post_install do |installer|
  # Remove -G flag from all build configurations
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["OTHER_CFLAGS"] = config.build_settings["OTHER_CFLAGS"].to_s.gsub(/-G/, "")
      config.build_settings["OTHER_CXXFLAGS"] = config.build_settings["OTHER_CXXFLAGS"].to_s.gsub(/-G/, "")
      config.build_settings["OTHER_LDFLAGS"] = config.build_settings["OTHER_LDFLAGS"].to_s.gsub(/-G/, "")
    end
  end
end
EOF
  fi
  echo "Modified Podfile to add post_install hook"
fi

# Run pod install with our compiler wrappers
echo "Running pod install with compiler wrappers..."
cd "$PROJECT_ROOT/ios"
pod install

# Get available iOS simulators
echo "Available iOS simulators:"
xcrun simctl list devices | grep -i iphone

# Automatically select a simulator (prefer booted ones)
# Extract the device ID properly using awk
DEVICE_ID=$(xcrun simctl list devices | grep -i iphone | grep -i "booted" | awk -F'[()]' '{print $2}' | head -n 1)

if [ -z "$DEVICE_ID" ]; then
  # If no booted simulator, get the first available one
  DEVICE_ID=$(xcrun simctl list devices | grep -i iphone | awk -F'[()]' '{print $2}' | head -n 1)
fi

if [ -z "$DEVICE_ID" ]; then
  echo "Error: No iPhone simulator found"
  exit 1
fi

echo "Using simulator device ID: $DEVICE_ID"

# Source the Xcode build modifier script to set up the environment
source "$PROJECT_ROOT/ios/modify_xcode_build.sh"

# Run Flutter directly with the specified device
echo "Running Flutter with modified environment..."
cd "$PROJECT_ROOT"
flutter run -d "$DEVICE_ID"
