#!/bin/bash

# This script runs Flutter with environment variables to bypass the -G flag issue
# It directly sets the necessary environment variables and specifies the iOS simulator device

set -e  # Exit on error

# Get the absolute path to the project root directory
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "Project root: $PROJECT_ROOT"

# Make sure compiler wrappers are executable
chmod +x "$PROJECT_ROOT/compiler_wrappers/clang" "$PROJECT_ROOT/compiler_wrappers/clang++"

# Add compiler wrappers to the beginning of PATH
export PATH="$PROJECT_ROOT/compiler_wrappers:$PATH"
echo "Modified PATH to use compiler wrappers:"
echo "PATH=$PATH"

# Set environment variables to force Xcode to use our compiler wrappers
export CC="$PROJECT_ROOT/compiler_wrappers/clang"
export CXX="$PROJECT_ROOT/compiler_wrappers/clang++"
export LDPLUSPLUS="$PROJECT_ROOT/compiler_wrappers/clang++"

# Set Flutter environment variables to modify the build process
export FLUTTER_XCODE_ONLY_ACTIVE_ARCH=YES
export FLUTTER_BUILD_MODE=debug

echo "Compiler environment variables set:"
echo "CC=$CC"
echo "CXX=$CXX"
echo "LDPLUSPLUS=$LDPLUSPLUS"
echo "FLUTTER_XCODE_ONLY_ACTIVE_ARCH=$FLUTTER_XCODE_ONLY_ACTIVE_ARCH"

# Run flutter pub get to ensure Flutter configuration files exist
echo "Running flutter pub get..."
flutter pub get

# Remove -G flag from xcconfig files
echo "Removing -G flag from xcconfig files..."
find "$PROJECT_ROOT/ios" -name "*.xcconfig" -exec sed -i '' 's/-G//g' {} \;

# Create a custom xcconfig file to override any remaining -G flags
echo "Creating custom xcconfig file..."
cat > "$PROJECT_ROOT/ios/Flutter/CustomBuild.xcconfig" << 'EOF'
// This file is generated by run_ios_fixed.sh
// It removes the -G flag from the build process

OTHER_CFLAGS = $(inherited)
OTHER_CXXFLAGS = $(inherited)
OTHER_SWIFT_FLAGS = $(inherited)

// Force the compiler to ignore the -G flag
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) DISABLE_G_FLAG=1
EOF

# Update Debug.xcconfig and Release.xcconfig to include our custom xcconfig
echo "Updating xcconfig files..."
for config_file in "$PROJECT_ROOT/ios/Flutter/Debug.xcconfig" "$PROJECT_ROOT/ios/Flutter/Release.xcconfig"; do
  if [ -f "$config_file" ]; then
    if ! grep -q "CustomBuild.xcconfig" "$config_file"; then
      echo '#include "CustomBuild.xcconfig"' >> "$config_file"
      echo "Updated $config_file to include CustomBuild.xcconfig"
    fi
  fi
done

# Run pod install with our compiler wrappers
echo "Running pod install with compiler wrappers..."
cd "$PROJECT_ROOT/ios"
pod install

# Get available iOS simulators
echo "Available iOS simulators:"
xcrun simctl list devices | grep -i iphone

# Ask the user to select a simulator or use the default one
echo ""
echo "Enter the simulator device ID to use (leave blank for default):"
read -r DEVICE_ID

if [ -z "$DEVICE_ID" ]; then
  # Get the first available booted simulator or the first available one
  DEVICE_ID=$(xcrun simctl list devices | grep -i iphone | grep -i "booted" | head -n 1 | sed -E 's/.*\(([A-Za-z0-9-]+)\).*/\1/')
  
  if [ -z "$DEVICE_ID" ]; then
    DEVICE_ID=$(xcrun simctl list devices | grep -i iphone | head -n 1 | sed -E 's/.*\(([A-Za-z0-9-]+)\).*/\1/')
  fi
  
  if [ -z "$DEVICE_ID" ]; then
    echo "Error: No iPhone simulator found"
    exit 1
  fi
  
  echo "Using simulator device ID: $DEVICE_ID"
fi

# Run Flutter directly with the specified device
echo "Running Flutter with modified environment..."
cd "$PROJECT_ROOT"
flutter run -d "$DEVICE_ID"
